# Kanvas is a distributed system with multiple databases, servers, and web browser clients
# For development, we can spin everything up via docker-compose


services:
  api-server-db:
    image: postgres
    ports:
      - 54320:5432
    environment:
      POSTGRES_USER: POSTGRES_USER
      POSTGRES_PASSWORD: POSTGRES_PASSWORD
  api-server:
    build: ./store-api-server
    ports:
      - 3005:3000
    links:
      - api-server-db
    environment:
      POSTGRES_HOST: api-server-db
      POSTGRES_USER: POSTGRES_USER
      POSTGRES_PASSWORD: POSTGRES_PASSWORD
      #POSTGRES_PORT: 54320
  # store_frontend:
  #   build: ./kanvas.front
  #   ports:
  #     - 3010:3000
  admin-api-server-db:
    image: postgres
    ports:
      - 54321:5433
    environment:
      POSTGRES_USER: POSTGRES_USER
      POSTGRES_PASSWORD: POSTGRES_PASSWORD
  admin-api-server:
    build: ./admin-api-server
    ports:
      - 3006:3001
    links:
      - admin-api-server-db
    environment:
      POSTGRES_USER: POSTGRES_USER
      POSTGRES_PASSWORD: POSTGRES_PASSWORD
      POSTGRES_HOST: admin-api-server-db
