attributes:
  name: string
  create_ready: boolean
  description: string
  image.png: string
  thumbnail.png: string
  price: number
  editions_size: number
  launch_at: date
  categories: number[]
  proposed: boolean
  publish: boolean


states:
  creation:
    state_transitions:
    - next_state: setup_nft
      when:
      - nft.name.length > 0
      - nft.create_ready
    mutables:
    - attributes: [name, create_ready]
      by_roles: [creator]

  setup_nft:
    state_transitions:
    - next_state: proposed
      when:
      - nft.proposed
      - nft.editions_size > 0
      - nft.price > 0
      - nft.categories.length > 0
      - nft.launch_at >= Date.now()
    mutables:
    - attributes: [price, editions_size, proposed, categories, launch_at]
      by_roles: [editor, creator, admin]

  proposed:
    state_transitions:
    - next_state: finish
      when:
      - nft.publish
      - nft['image.png'].length > 0
      - nft['thumbnail.png'].length > 0
      - nft.description.length > 0
    mutables:
    - attributes: [publish, image.png, thumbnail.png, description]
      by_roles: [moderator, admin]
