attributes:
  price: Number
  editions_size: Number
  categories: 'eval'
  proposed: Boolean
  proposal_pass: '[user]'
  proposal_reject: '[user]'
  prototype_pass: '[user]'
  prototype_reject: '[user]'

# notes:
# - mutable integers have set,unset
# - mutable booleans have set,unset
# - mutable [..] have add,unset
# - [..] are probably going to be sets, not lists



states:
  setup_nft:
    state_transitions:
    - next_state: proposed
      when: '
        return
          nft.proposed &&
          nft.editions_size > 0 &&
          nft.price > 0 &&
          nft.categories.length > 0;'
      do: '{
        delete nft.proposed;
        ext.testFunction(555);
        delete nft.editions_size;
      }'
    mutables:
    - attributes: [price, editions_size, proposed, categories]
      by_roles: [editor, creator]


  proposed:
    state_transitions:
    - next_state: setup_nft
      when: 'nft.proposal_rejects.length > 0'
      do: 'nft.proposed = false'

    - next_state: prototype
      when: 'nft.proposal_accepts.length == 3'

    mutables:
    - attributes: [proposal_accepts, proposal_rejects]
      by_roles: [moderator]


  prototype:
    state_transitions:
    - new_state: finish
      when: 'nft.prototype_accepts.length == 3'

    - new_state: setup_nft
      when: 'nft.prototype_rejects.length > 0'

    mutables:
    - attributes: [prototype_accepts, prototype_rejects]
      by_roles: [moderator]
